### ISSUE TITLE
Inviting users with capital letters in there mail address without mail enabled will fail to register

### ISSUE THREAD

**Issue by frankenstein91** [dani-garcia/vaultwarden#1963]
Inviting users with capital letters in there mail address without mail enabled will fail to register

see Matrix chat for more information

**Comment by BlackDex** [comment]
Confirmed.
The issue is that the mail addresses are not stored with lower-case letters within the invitations table.
Here: https://github.com/dani-garcia/vaultwarden/blob/main/src/db/models/user.rs#L352-L356 there is no conversion to lower-case, while here, https://github.com/dani-garcia/vaultwarden/blob/main/src/db/models/user.rs#L76-L79 it does.

And here are two different data paths used: https://github.com/dani-garcia/vaultwarden/blob/main/src/api/admin.rs#L269-L274

We need to make sure that all that info is lower-case stored and checked, and that the same data source is used for all items.

**Comment by BlackDex** [comment]
Workaround for now: Invite users only with lower-case e-mail addresses.
