### ISSUE TITLE
Importing multiple times results in duplicate folders

### ISSUE THREAD

**Issue by gdekeijzer** [dani-garcia/vaultwarden#2005]
When importing a CSV file in multiple sets because (copy/paste) of size, an existing folder is not recognized and created duplicate.
![image](https://user-images.githubusercontent.com/3164475/134981707-47686709-92fa-4a75-94aa-7030af8669e9.png)

Using v2.21.1

**Comment by gdekeijzer** [comment]
v2.21.1

**Comment by BlackDex** [comment]
This is not something we can fix because of multiple reasons.
1. The web-vault does the importing and encrypts it, no plain/text is send over. And the web-vault is not maintained by us 
2. Why do you import it twice??

The main reason is, the import of the web-vault encrypts each value separately, and thus no match can be made on the server side at all.

**Comment by gdekeijzer** [comment]
Thanx, that makes sense indeed.

I had trouble importing a large CSV file (550 passwords)
But i got it figured out. Had to do with a timeout at my reverse proxy.
This issue can therefore be closed/canceled.
