### ISSUE TITLE
SIGNUPS_ALLOWED not stopping new user creation

### ISSUE THREAD

**Issue by JBFUK** [dani-garcia/vaultwarden#2028]
### Subject of the issue

SIGNUPS_ALLOWED not stopping new user creation

### Deployment environment

Latest Docker Image

* Install method: Docker Compose

* Clients used: Web-Vault

* Reverse proxy and version: Nginx

* MySQL/MariaDB or PostgreSQL version: MariaDB

* Other relevant details:

### Steps to reproduce
Set environment variable SIGNUPS_ALLOWED=false via docker-compose file

### Expected behaviour
Expect new user creation from the main login page to fail with an error (as described in WIKI)

### Actual behaviour
Allows new user creation and subsequent login

**Comment by jjlin** [comment]
You probably have `SIGNUPS_DOMAINS_WHITELIST` set as well.

See https://github.com/dani-garcia/vaultwarden/wiki/Disable-registration-of-new-users#restricting-registrations-to-certain-email-domains.

**Comment by jjlin** [comment]
These settings were implemented by different people at different times, so the design is not always the most cohesive.

`SIGNUPS_DOMAINS_WHITELIST` is documented as

https://github.com/dani-garcia/vaultwarden/blob/9930a0d75224202dbc355e945724aa545bedebe2/.env.template#L179-L181

The original implementation required `SIGNUPS_ALLOWED=false` to be set. Since the default is `SIGNUPS_ALLOWED=true`, a quite common issue was to set only `SIGNUPS_DOMAINS_WHITELIST` and expect that to limit the signups, which wasn't how it worked. So later `SIGNUPS_DOMAINS_WHITELIST` was changed to simply override `SIGNUPS_ALLOWED`, because why would you set `SIGNUPS_DOMAINS_WHITELIST` if you didn't expect that to control signups?

If you're interested in proposing and implementing another design that is still backward compatible, feel free.

**Comment by pepa65** [comment]
Backward compatible meaning: we keep the same variables and the current results need to stay as they are? And then introduce new variables to attain the same range of outcomes more sensibly??

I think the outcomes I listed are fairly useful, and with the 3 boolean variables, there are only 2 outcomes that are overlapping, ie. if SIGNUPS_ALLOWED [S] and INVITATIONS_ALLOWED are both false, the value of SIGNUPS_DOMAINS_WHITELIST is irrelevant, and that makes sense.

@jjlin My proposal would be along the lines of the list of outcomes in my previous post. Do you think that is workable?

**Comment by jjlin** [comment]
I would say backward compatible means something that is expected to remain working for the vast majority of existing deployments.

Given the existing constraints and the fact that people can achieve the desired results if they read the docs, I'm not sure polishing this a lot is worth the effort, and it's not work I'm personally interested in. But other people who feel strongly about it are certainly welcome to step up.

**Comment by pepa65** [comment]
I guess the bug reported would need to set all 3 to FALSE to achieve his desired outcome. I all desired outcomes are already achievable, we can let this rest, until someone want to achieve something that the current setup does not cater to. Example: wanting to allow invitations that are limited to the whitelist but no self-signup. Then it could be fixed, but warn people with exisiting installations that Vaultwarden got a bit more specific.

**Comment by BlackDex** [comment]
Did you do a `docker-compose up -d` after you modified it?
If not, these changes didn't had any effect.

Please go to `/admin/diagnostics` and generate a support string there, so that we can see the running config.

**Comment by BlackDex** [comment]
I think you actually need to change your docker-compose file.
```yml
environment:
  - TZ=UTC
  - DOMAIN=https://my.domain.tld
  - SIGNUPS_ALLOWED=false
  - ADMIN_TOKEN=${SECRET_ADMIN_TOKEN}
  - RUST_BACKTRACE=1
```

You have quotes `"` around the whole values, i think that breaks it in some way.
And i even think it is not using MySQL this way, but that I'm not sure.
