### ISSUE TITLE
This project contains known security vulnerabilities

### ISSUE THREAD

**Issue by euDominic** [dani-garcia/vaultwarden#2425]
This project contains known security vulnerabilities
https://deps.rs/repo/github/dani-garcia/vaultwarden
Dependencies
(50 total, 4 outdated, 1 insecure)

**Comment by BlackDex** [comment]
Yea, which we can't resolve.
Chrono is currently having some development done to try and resolve that issue.
Also, it could be unsound to use, it isn't something very trivial i think.

And regarding the others, we can't update some of them since we need to wait for some other packages to be  updated first since they are dependent on each other.

Since we always try to use the latest versions of the crates available i do not think this issue should be kept open.

I already have a local testing version with some of the updated crates and all works fine.
As I'm also working on some other optimizations it is probably better to try and merge them all together.

But, thanks for the reminder.
