### ISSUE TITLE
Bug disappearance subfolders in left pane

### ISSUE THREAD

**Issue by Nyxtorm** [dani-garcia/vaultwarden#2569]
### Subject of the issue

Folders w/ subfolders disappear in left pane when I click on organization where I am the owner.

### Deployment environment

* Vaultwarden version: v1.25.0-887e320e (and tested with last PR 2567 as well)
* Web-vault version: v2022.5.2
* Running within Docker: false (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4
* Clients used: Web, Android, Windows, Chrome, Firefox
* Reverse proxy and version: Nginx 1.21.6
* Other relevant information: 

### Steps to reproduce

1. Have **subfolders** and basic folders in your vault with items 
2. In the "Vault" tab, we see the whole list of folders, including folders with subfolders in the left pane.
3. Click on the organization you own in the top left pane
4. Only folders with subfolders disappear from the listing in the left pane

### Expected behaviour / Actual behaviour

All folders should be displayed when I choose an organization in left pane 

### Troubleshooting data

Sorry for my English.

**Comment by BlackDex** [comment]
Looks like this is an upstream issue, i see the same on the Official Bitwarden instances happening, though not with subfolders for me. But i see folders disappearing when clicking other organizations, also doesn't matter if I'm owner, admin, manager or user of an organization.

I'm afraid we can't fix this issue on the server side.

**Comment by Nyxtorm** [comment]
Hello @BlackDex,

I tried to reproduce the problem on the official vault to open an issue but I can't reproduce it. Do you know if there is already an issue open for this?

Because unfortunately I don't have enough precise information to give them to try to correct this problem.

**Comment by BlackDex** [comment]
@Nyxtorm When did you tried this?
They have just released a new version of the web-vault (which i was planning to patch for Vaultwarden in a few moments).
There are some fixes done there regarding filtering, which could have fixed the current bug :).

The current version is 2022.6.0, Vaultwarden latest now is 2022.5.2

**Comment by Nyxtorm** [comment]
I can confirm the documentation is correct for the build (very manual way) with the PR72, I'm well in 2022.6.0, unfortunately the problem of disappearing folders is still present. :(

**Comment by BlackDex** [comment]
Regarding the git+ssh, that is probably something upstream is best to fix. It also doesn't seem to affect the Dockerfile build, which also does not have an SSH key, since that an anonymous user.

Regarding the issue it self, that is still an issue of Upstream it looks like, i tested it on an updated self-hosted `v2022.6.0` version, and it also still happens there.

It also happens if i use there build of the web-vault, which you can extract here: https://github.com/bitwarden/clients/releases/tag/web-v2022.6.0

Download the `web-2022.6.0-selfhosted-open-source.zip`, extract the files within the `build` folder to the web-vault folder.
It will not have the Vaultwarden patches, but unless you use a sub-path, this should work with most functionality.
And there i have exactly the same. So, it looks like an issue on the web-vault it self.

**Comment by Nyxtorm** [comment]
Thank you for all these details. I also noticed in the meantime that the problem occurs on the Windows client and even on the browser client Chrome (and possibly elsewhere).

The problem could be beyond the web vault (unless these clients only rely on the web vault part, I'm not expert enough to know that).

To be continued! :)

**Comment by BlackDex** [comment]
If it also happens there it's a bug in the `jslibs`, or rather the `libs` directory currently in the `clients` repo.
