### ISSUE TITLE
Global rules contains sonyentertainmentnetwork.com twice

### ISSUE THREAD

**Issue by nielsbasjes** [dani-garcia/vaultwarden#3149]
The global domain rules contains sonyentertainmentnetwork.com in 2 lists.
Once with sony.com and once with playstation.com

https://github.com/dani-garcia/vaultwarden/blob/main/src/static/global_domains.json#L405
https://github.com/dani-garcia/vaultwarden/blob/main/src/static/global_domains.json#L897

To me it seems that these 3 should be combined into a single list.
Is my assessment correct?

**Comment by BlackDex** [comment]
We use a tool https://github.com/dani-garcia/vaultwarden/blob/9b7e86efc23d6bbb5ee350160085ab8d8421d628/tools/global_domains.py

Which extracts the data from the official Bitwarden data located here
https://github.com/bitwarden/server/blob/master/src/Core/Enums/GlobalEquivalentDomainsType.cs and  https://github.com/bitwarden/server/blob/master/src/Core/Utilities/StaticStore.cs

Which states both, ans they have different main domains.
So i think it's valid. If you think otherwise, i suggest to report this at Bitwarden.
