### ISSUE TITLE
Migrations cause Postgres warnings because SET CONSTRAINTS can only be used in transaction blocks

### ISSUE THREAD

**Issue by spantaleev** [dani-garcia/vaultwarden#3930]
Each time Vaultwarden starts, it runs its migrations and those trigger a Postgres warning (logged in the Postgres logs):

> WARNING: SET CONSTRAINTS can only be used in transaction blocks

### Deployment environment

* vaultwarden version: 1.29.2

* Install method: Docker image

* Clients used: irrelevant

* Reverse proxy and version: irrelevant

* MySQL/MariaDB or PostgreSQL version: PostgreSQL v16

* Other relevant details:

I've found this code to be related: https://github.com/dani-garcia/vaultwarden/blob/bc26bfa589c007da9b9be37e1172060f38a948b9/src/db/mod.rs#L493

It doesn't seem like Vaultwarden is affected negatively by this, but it's probably something that should be looked into anyway.

### Steps to reproduce

Restart Vaultwarden. On startup, it will run its migrations code and trigger this warning (found in the Postgres logs).

**Comment by stefan0xC** [comment]
According to the comment preceding the statement (and the linked documentation) https://github.com/dani-garcia/vaultwarden/blob/bc26bfa589c007da9b9be37e1172060f38a948b9/src/db/mod.rs#L487-L492 it does not do anything outside a transaction, so it can be ignored.
((And possible removed since `run_pending_migrations` will [run each migration in its own transaction](https://docs.diesel.rs/1.4.x/diesel_migrations/fn.run_pending_migrations.html))
