### ISSUE TITLE
Testing version differ from latest commit in diagnostic admin panel

### ISSUE THREAD

**Issue by danielphan2003** [dani-garcia/vaultwarden#4226]
### Subject of the issue
The diagnostic page is showing an update from `latest` commit (https://github.com/dani-garcia/vaultwarden/commit/ae3a153bdb062414402ec94901fabb1105838674), but this commit doesn't actually cause the CI to build a new testing image that I could update to.

I think the diagnostic panel is checking the latest git commit, instead of the latest CI build that is available.

### Deployment environment

* Vaultwarden version: v1.30.1-2c369937
* Web-vault version: v2023.12.0
* OS/Arch: linux/x86_64
* Running within Docker: false (Base: Not applicable)

### Steps to reproduce

Use the testing build.

### Expected behaviour

Diagnostic page should show there is no update available.

### Actual behaviour

There seems to be an update as indicated on the page, but there is actually none.

### Troubleshooting data

![Actual behaviour](https://github.com/dani-garcia/vaultwarden/assets/34669737/632ad31d-96ed-4b37-a568-9791ed869775)

![An image comparing the commit between deployment environment version versus the latest commit](https://github.com/dani-garcia/vaultwarden/assets/34669737/6d29e1b9-d526-463a-891f-1386f7b4b340)

**Comment by stefan0xC** [comment]
> I think the diagnostic panel is checking the latest git commit, instead of the latest CI build that is available.

That is indeed what is done:
https://github.com/dani-garcia/vaultwarden/blob/ae3a153bdb062414402ec94901fabb1105838674/src/api/admin.rs#L620-L624

The question to me would be if we should fix this (which would probably not be trivial) or if this discrepancy is an acceptable shortcoming we can dismiss because it's not that big of an issue which will only come up if the latest commit did not trigger a release
https://github.com/dani-garcia/vaultwarden/blob/ae3a153bdb062414402ec94901fabb1105838674/.github/workflows/release.yml#L5-L16

Personally I think it's not worth the effort (but I have not looked into the [GitHub API](https://docs.github.com/en/rest/actions?apiVersion=2022-11-28) if there's an easy way to check for the commit of just the latest Release workflow).

**Comment by BlackDex** [comment]
I did some checking. And it isn't possible to extract the last build version via an API call.
Also tried to check the packages if i could use that, but that is also not an option.

Only option i can think of is by using the artifacts maybe.
We could add an extra artifact with every release workflow like a file called testing or something.
That is easy to filter since the API even has a `?name=testing` option. We can then use that response to get the latest build hash.

That might be an option.
I Was planning on doing some (larger) updates on the admin interface.
Ill see if i can take this into account to make it more robust.
And, to be on the safe side, i will use the current way as a fallback probably, in case the artifacts are not there anymore for some reason

**Comment by dani-garcia** [comment]
Could we just rebuild the images all the time, even if the changes are only to the readme? I can't imagine those kinds of non-source code changes happen very often anyway, so it's not like we're saving a lot of build time.

**Comment by BlackDex** [comment]
Ill fix that right away. That is very easy to do :)

**Comment by BlackDex** [comment]
Done via #4309
