### ISSUE TITLE
[Bug] Latest testing, collections do not load (Related to PascalCase changes?)

### ISSUE THREAD

**Issue by jb2barrels** [dani-garcia/vaultwarden#4682]
### Subject of the issue

Collections tree in the filters box does not show all collections after upgrading to latest testing. (Maybe related to the latest PascalCase changes?)

### Deployment environment

* vaultwarden version: testing (Latest) - As of June 27 2024

* Install method: Docker Compose

* Clients used: 
Web vault

* Reverse proxy and version: 
Nginx Proxy Manager with SSL

### Expected behaviour

Collections tree should load under the filters section.

Example screenshot, where it shows collections do exists but do not show up in the collections tree on the left.
![image](https://github.com/dani-garcia/vaultwarden/assets/129100561/8b8bcaa5-628d-49fc-99e7-2d17abb1bb26)

**Comment by BlackDex** [comment]
Probably related to #4681, but could be something different.

**Comment by stefan0xC** [comment]
It also happens on vault.bitwarden.com so this probably unrelated to vaultwarden (might even be intentional).

**Comment by jb2barrels** [comment]
> It also happens on vault.bitwarden.com so this probably unrelated to vaultwarden (might even be intentional). cf. [bitwarden/clients#9823](https://github.com/bitwarden/clients/issues/9823)

I was able to rollback to the June 20th build of vaultwarden (via doing a docker build):
https://github.com/dani-garcia/vaultwarden/commit/8f05a90b96adfe06722d01510923759fe61a8bd6

So it seems the issue crept in on vaultwarden between June 23rd - June 24th.
I don't see a web vault update between those dates, so I do wonder if the above is a coincidene or some recent change that was somewhat copied over from Bitwarden into Vaultwarden.

**Comment by stefan0xC** [comment]
seems like this setting is responsible for the behavior: https://github.com/dani-garcia/vaultwarden/blob/a4c7fadbf4ffa242fb78ebd152080028e7f2993c/src/db/models/organization.rs#L409

**Comment by BlackDex** [comment]
Ah, we can set that back to false for now. And add flex/v2 later.

**Comment by stefan0xC** [comment]
> Ah, we can set that back to false for now. And add flex/v2 later.

I don't think those two are that related (like I said https://github.com/dani-garcia/bw_web_builds/pull/169#issuecomment-2185324417 the new endpoint is already used instead). To actually implement flexible collections we will have to change more stuff (not sure if this is everything but that's what I've noted down so far)
- [ ] Implement Custom User Permissions
- [ ] Deprecate Manager role and write migration to set new "can manage" permission over assigned collections.
- [ ] Deprecate "Access All" Flag and write migration to apply "can manage" permission to all collections.
- [ ] Add new `/api/organizations/<org_uuid>/collections/bulk-access` endpoint for new bulk collection assignment
- [ ] Support option to limit creation/deletion of collections to owners/admins.
- [ ] Adapt the `collections_v2` endpoint to return `"unvailable": true` if the cipher becomes unavailable due to changed permissions.

**Comment by BlackDex** [comment]
I created a PR to fix this specific issue, and a small issue i found with the new native app. #4685
