### ISSUE TITLE
Manager Role no long has ability to manage collection access

### ISSUE THREAD

**Issue by dwestness** [dani-garcia/vaultwarden#4844]
### Subject of the issue
Manager Role no longer has ability to manage collection access

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.32.0
* Web-vault version: v2024.6.2b
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Forwarded-For)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.46.0

### Steps to reproduce
We recently noticed (after updating to version 1.32.0, but could have existed prior to this version unnoticed) that the Manager role no longer has the ability to view/manage the members of an existing collection. It does appear that this role does permit the creation of a new collection and the assignment of members during creation, but then loses all ability to view/manager post-creation as well.

### Expected behaviour
Manager role would be able to view/manager collection members as described in the role description.

### Actual behaviour
Each collection under an organization no longer as the "..." 3-dots menu to navigate to the access settings of the collection when signed in with a manager role for the organization

**Comment by stefan0xC** [comment]
Thanks for the report. It seems that this is due to the [ongoing deprecation of the Manager role](https://bitwarden.com/help/user-types-access-control/#member-roles) (which Bitwarden has removed in `v2024.7.x` completely) and switching to a permission system (which we currently don't really have implemented). https://github.com/dani-garcia/vaultwarden/blob/9eebbf3b9f6ad6002353014148057049976be3d1/src/db/models/organization.rs#L348-L365

In earlier versions not returning the correct permissions did not matter but apparently with `v2024.6.x` the Bitwarden web-vault does not take the Manager role into account anymore (while still having it).

**Comment by BlackDex** [comment]
I'm looking into fixing this a.t.m. As this does make it a hard to manage Vaultwarden for some users i think.

**Comment by BlackDex** [comment]
Ok, I think i have a fix ready for this issue via #4860
